version: '3'

services:
    fewww:
        build: ../artifacts/nginx
        container_name: fewww
        networks:
            - thenet
        links: 
            - feapp:feapp
    feapp:
        build: ../artifacts/filebrowser/
        container_name: feapp
        networks:
            thenet:
                aliases: 
                    - feapp
            dbnet:
        ports:
            - '8080:8080'
        depends_on:
            - database
    database:
        image: "postgres:9.6.5"
        container_name: "database"
        volumes:
            - "dbdata:/var/lib/postgresql/data"
        env_file:
            - ../conf/dev/database.env
        hostname: db.devops.ae
        networks: 
           dbnet:
             aliases: 
                - db.devops.ae

networks:
    thenet:
        driver: bridge
    dbnet:
        driver: bridge

volumes:
  dbdata:

