#FROM ubuntu

FROM nginx:alpine
 
#RUN apt-get update 
#RUN apt-get install -y apt-utils


#RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
#RUN apt-get install -y -q


#RUN \
#  apt-get install -y nginx

#WORKDIR /etc/nginx

COPY nginx.conf /etc/nginx/nginx.conf

#CMD ["nginx"]

#EXPOSE 80
#EXPOSE 443
